### ISSUE TITLE
Vấn đề re-render

### ISSUE THREAD

**Issue by HoaiHuynh** [ghun131/use-selector-and-connect#4]
Chào anh, em đang sử dụng useSelector cho project React Native của mình, em đang gặp phải 1 vấn đề đó là khi em dispatch 1 action ở Màn hình 1, và sau đó qua Màn hình 2 dispatch 1 action khác thì dữ liệu của màn hình 1 lấy được từ lúc dispatch action bị mất, và dẫn đến tình trạng re-render màn hình 1. Cho em hỏi đây có phải do useSelector gây ra như anh nói không ạ? và cách fix lỗi này như nào? Mong anh giải đáp

**Comment by ghun131** [comment]
Hi bạn, mình nghĩ bạn thử dùng `connect` xem còn bị vấn đề này không. Nếu không bị chứng tỏ `useSelector` gây ra còn nếu vẫn bị thì rất có thể do yếu tố khác.
